
services:
  vymanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend port
      - "8000:8000"  # Backend API port
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=8000
      - FRONTEND_PORT=3000
    volumes:
      - ./.env:/app/config/.env:ro  # Mount .env file as read-only
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/show/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 